---
- hosts: "{{ variable_hosts }}"

  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        update_cache: yes
        state: latest

    - name: install latest version of docker
      shell: sudo amazon-linux-extras install docker selinux-ng -y

    - name: install container-selinux
      yum:
        name: 'container-selinux'
        state: latest

    - name: host access granted
      lineinfile:
        path: /etc/hosts.allow
        state: present
        regexp: '^sshd'
        line: 'SSHD: 127.0.0.0/27'

    - name: host access denied
      lineinfile:
        path: /etc/hosts.deny
        state: present
        regexp: '^ALL'
        line: 'ALL: ALL'

    - name: Enable SElinux
      selinux:
        policy: targeted
        state: enforcing

    - name: update docker configure
      copy:
        src: docker-daemon.json
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: 644
      notify:
        - restart docker

    - name: change security contexts
      shell: /usr/bin/chcon -R -t container_var_lib_t /data/docker && /usr/bin/chcon -R -t container_share_t /data/docker/overlay2
      notify:
        - restart docker

  handlers:
    - name: restart docker
      service:
        name: docker
        enabled: yes
        state: restarted
