---
# This role login repo for aws ecr

- name: Login ecr
  shell:/usr/bin/aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin "{{ env_repos }}/{{ env_file}}-{{ project_name }}"
  register: check

- name: Show login
  debug:
    var: check.stdout-lines
